### ISSUE TITLE
Change "Building" to "Dorm"

### ISSUE THREAD

**Issue by Elliott03** [Elliott03/UCReviews#10]
Change the name of the "Building" table to "Dorm" to make it clearer. Also update the codebase to reflect this.

**Comment by whsiq** [comment]
- When updating the codebase do I need to rename ALL instances of "Building" to "Dorm"? Or would it make sense to keep some named "Building"?
- BuildingId FK in Review table -> DormId?

**Comment by whsiq** [comment]
> * When updating the codebase do I need to rename ALL instances of "Building" to "Dorm"? Or would it make sense to keep some named "Building"?
> 
>     * BuildingId FK in Review table -> DormId?

Change all instances of "Building" to "Dorm" - make sure to change file names for classes
Change name of BuildingId to DormId
